### ISSUE TITLE
cd and other command not working

### ISSUE THREAD

**Issue by medmouine** [fclairamb/afero-s3#117] opened 2020-10-19 15:07 UTC
Hi, we have been using this library at my job for managing s3 buckets as an FTP client.
We are having some issues concerning the `cd` command as it throws a 550 error whenever our application calls the fs.
```
550 CD issue: stat /<directory_name>: InternalServerError: Internal Server Error\n	status code: 500
```
After investigation, we concluded this error was originating from this library.
We do know that s3 does not support directories but we expected the naming standard `/directory/file.ex` to handle the navigation feature.

Is this a known issue and can you provide any support about this?

Thank you

**Comment by fclairamb** [comment] 2020-12-16 02:18
Hi @medmouine,

Sorry for the late response.

Can you give me a way to reproduce this? Or at least the succession of FTP commands that lead to getting this error?

I guess you mean you're using the [ftpserver](https://github.com/fclairamb/ftpserver) with this S3 integration.

What I can tell you is that this is definitely supposed to work. I did a test on an actual S3 bucket by uploading this file from an FTP client and then accessing it:
```text
ncftp ftp://s3:s3@localhost:2121/
NcFTP 3.2.6 (Dec 04, 2016) by Mike Gleason (http://www.NcFTP.com/contact/).
Connecting to 127.0.0.1...                                                                                                                                                                
ftpserver
Logging in...                                                                                                                                                                             
Password ok, continue
Unknown command                                                                                                                                                                           
Logged in to localhost.                                                                                                                                                                   
Current remote directory is /.
ncftp / > cd directory
CD worked on /directory
ncftp /directory > ls
file.ex
ncftp /directory > get file.ex
file.ex:                                                15,43 MB   25,80 MB/s  
ncftp /directory > 
```

**Comment by fclairamb** [comment] 2021-02-14 21:35
@medmouine I'm closing this issue as I can't reproduce it. 

I'm wondering if it's not related to #97.

On what OS were you when you faced it?

**Closed by fclairamb** 2021-02-14 21:35 UTC

**Comment by medmouine** [comment] 2021-02-16 15:13
Hi, @fclairamb sorry for the delay. We found out that the issue was coming from the Java FTP client we used and not `afero-s3`.
